### ISSUE TITLE
Links to our lessons not working from within learnr

### ISSUE THREAD

**Issue by braunsb** [ianmcampbell/Arcus-Modular-Education-Support-System#7] opened 2019-11-11 13:45 UTC
Here is the text from the lesson: 

 [One-Sample _t_ Test]("http://www.a-mess.org/sb-one-sample-t-test/) and [Two-Sample _t_ Test]("http://a-mess.org/sb-two-sample-t-test/").

Here is the link that gets called:

http://www.a-mess.org/sb-paired-t-test/%22http://a-mess.org/sb-two-sample-t-test/%22

**Comment by ianmcampbell** [comment] 2019-11-11 16:22
Duplicate of #5

**Closed as completed by ianmcampbell** 2019-11-11 16:22 UTC
Labels: duplicate
